out_dir: results
name_tag: 5x5x1_with_dim_96_RWSE_2layersEncoder_1000epochs_unnormalized.1run
metric_best: mae
metric_agg: argmin
wandb:
  use: True
  project: ZINC
dataset:
  format: PyG-ZINC
  name: subset
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode+RWSE
  node_encoder_num_types: 28
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 4
  edge_encoder_bn: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 24
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 32   
  eval_period: 1
  ckpt_period: 100
model:
  type: HMNModel
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
gnn:
  head: san_graph
  MaskEncoder_type: "Graph_Invariant"
  GIMaskEncoder_layers: 2
  GIMaskEncoder_raw_norm_type: none
  GIMaskEncoder_hidden_dim: 8
  GIMaskEncoder_graph_invariant: ["degree", "pagerank"]
  GIMaskEncoder_batch_norm: True 
  GIMaskEncoder_normalize: False
  HeatConvBlock_n_layers: 1

  layers_pre_mp: 0
  layers_block: 5
  layers_post_mp: 3
  dim_inner: 96
  batchnorm: True
  residual: True
  sublayer_residual: True
  num_clusters: 5
  train_eps: True
  act: relu
  dropout: 0.0
  agg: sum
  normalize_adj: False
optim:
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 1000
  scheduler: cosine_with_warmup
  num_warmup_epochs: 50
  min_lr: 1e-6
